# Basic info
title: b-marker Blog
tagline: b-marker-dev & team
description: Our Logs and team works.
timezone: Asia/Taipei

# About
author:
  name: Gary Chiu
  avatar: https://github.com/b-marker-dev.png
  email: dev@b-marker.com

# Theme setting
theme: minima
lang: zh-TW 
# turn on dark mode
darkmode: true
# auto
toc: true
# social
social:
  github: https://github.com/b-marker-dev
